description: >
  Clone repo and build container.

steps:
  - run:
      name: Download and unzip the repo
      command: |
        curl -sL https://github.com/cloudflare/flan/archive/master > master.tar
        tar xvzf master.tar --strip-components 1
        rm master.tar
  - setup_remote_docker:
      version: 19.03.13
  - run:
      name: Build the docker container
      command: |
        make build
