description: >
  Clone repo and build container.

steps:
  - run:
      name: Download and unzip the repo
      command: |
        curl -soL master.tar.gz https://github.com/cloudflare/flan/tarball/master
        tar xvzf master.tar.gz --strip-components 1
        rm master.tar.gz
  - setup_remote_docker:
      version: 19.03.13
  - run:
      name: Build the docker container
      command: |
        make build
