description: >
  Clone repo and build container.

steps:
  - run:
      name: Install git client
      command: apk add git
  - run:
      name: Clone the repository
      command: |
        git clone https://github.com/cloudflare/flan
        cd flan
