description: >
  Clone repo and build container.

parameters:
  ip:
    type: string
    default: "1.1.1.1"
    description: "The target IP address to scan"

steps:
  - run:
      name: Download and unzip the repo
      command: |
        curl -sL https://github.com/cloudflare/flan/tarball/master > master.tar.gz
        tar xvzf master.tar.gz --strip-components 1
        rm master.tar.gz
        echo <<parameters.ip>> > shared/ips.txt
  - setup_remote_docker:
      version: 19.03.13
  - run:
      name: Build the docker container
      command: |
        make build
