description: >
  Clone repo and build container.

steps:
  - setup_remote_docker:
      version: 19.03.13
  - run:
      name: Download and unzip the repo
      command: |
        curl -sLO https://github.com/cloudflare/flan/archive/master.zip
        unzip master.zip
        cd flan-master
  - run:
      name: Build the docker container
      command: make build
